/**:
  ros__parameters:
    # Topics
    pointCloudTopic: "/livox/lidar"               # Point cloud data
    imuTopic: "/livox/imu"                          # IMU data
    odomTopic: "odometry/imu"                    # IMU pre-preintegration odometry, same frequency as IMU

    # Frames
    lidarFrame: "laser_sensor_frame"
    baselinkFrame: "base_link"
    odometryFrame: "odom"
    mapFrame: "map"

    # Heading
    useImuHeadingInitialization: false             # if using GPS data, set to "true"

    # Export settings
    savePCD: false                                # https://github.com/TixiaoShan/LIO-SAM/issues/3
    savePCDDirectory: "/Downloads/LOAM/"          # starts and ends with "/". Warning: deletes folder

    # Lidar Settings
    timeField: "timestamp"                        # point timestamp field
    downsampleRate: 1                             # downsample data if too many points
    lidarMaxRange: 50.0
    lidarMinRange: 0.5
    NUM_OF_CAM: 2
    fovMinTheta: 36.0
    fovMaxTheta: 98.0
    VRES: 40 # vertical and horizontal resolution for organizing point cloud
    HRES: 2000

    # IMU Settings
    imuAccNoise: 0.03015059
    imuGyrNoise: 0.42306179
    imuAccBiasN: 0.00198931
    imuGyrBiasN: 0.00015932
    imuGravity: 9.8
    imuRPYWeight: 0.01

    # Extrinsics (lidar -> IMU)
    extrinsicTrans:  [ 0.0,  0.0,  0.0 ]
    extrinsicRot:    [ 1.0,  0.0,  0.0,
                       0.0,  1.0,  0.0,
                       0.0,  0.0,  1.0 ]
    extrinsicRPY: [ 1.0,  0.0,  0.0,
                    0.0,  1.0,  0.0,
                    0.0,  0.0,  1.0 ]

    imuGravityScale: -9.8

    # LOAM feature threshold
    edgeThreshold: 1.0
    surfThreshold: 0.1
    edgeFeatureMinValidNum: 10
    surfFeatureMinValidNum: 100

    # Voxel filter parameters
    odometrySurfLeafSize:  0.4                    # default: 0.4 - outdoor, 0.2 - indoor
    mappingCornerLeafSize: 0.2                    # default: 0.2 - outdoor, 0.1 - indoor
    mappingSurfLeafSize:   0.4                    # default: 0.4 - outdoor, 0.2 - indoor

    # Robot motion constraint
    z_tolerance: 1000.0       # meters
    rotation_tolerance: 1000.0 # radians

    # CPU Params
    numberOfCores: 4
    mappingProcessInterval: 0.15

    # Surrounding map
    surroundingkeyframeAddingDistThreshold: 1.0
    surroundingkeyframeAddingAngleThreshold: 0.2
    surroundingKeyframeDensity: 2.0
    surroundingKeyframeSearchRadius: 50.0

    # Loop closure ... disabled, do that in VINS TODO ----
    loopClosureEnableFlag: False
    loopClosureFrequency: 1.0                     # Hz, regulate loop closure constraint add frequency
    surroundingKeyframeSize: 25
    historyKeyframeSearchRadius: 20.0
    historyKeyframeSearchTimeDiff: 30.0
    historyKeyframeSearchNum: 25
    historyKeyframeFitnessScore: 0.3

    # Visualization
    globalMapVisualizationSearchRadius: 1000.0
    globalMapVisualizationPoseDensity: 10.0
    globalMapVisualizationLeafSize: 1.0

    # check
    paramsCheck: 69
